### PR TITLE
[Cookie] Parallel NPM Install RackHD during CI src based test

### PR DESCRIPTION
**Pull request by panpan0000**
**Purpose**
improve the speed of function-tests, by parallel npm install the src code

**Implementation**
just run "npm install" in multiple process in background, and wait their result asynchronously

**Other Changes**
add description for this script

**Test Result**
Done by run script alone. this PR's PR Gate also use this new change and succesfful.

**Reviewer**
@PengTian0

### CODE REVIEW

**Comment by panpan0000** [comment]
PR Gate has prove this PR's validity: http://rackhdci.lss.emc.com/blue/organizations/jenkins/on-build-config/detail/on-build-config/616/pipeline/86/
But in some case, the npm-install-time become 2 min+, but sometimes still 5 min.
it may be VM Slave performance problem...

still need to dig with more data .

**Comment by panpan0000** [comment]
test this please

**Comment by PengTian0** [comment]
:+1:

**Comment by panpan0000** [comment]
[PR Gate b667](http://rackhdci.lss.emc.com/blue/organizations/jenkins/on-build-config/detail/on-build-config/667/pipeline/84)  shows the effect:
image


@iceiilin  @anhou

**Review by iceiilin — APPROVED** [review]

**Pull request merged**
