### PR TITLE
retry clone and npm install

### PR DESCRIPTION
**Pull request by PengTian0**
RAC5052: 
npm install`, `pip install`， `git clone` fail
Npm install fail, it's unstable AI: @Tian add retry mechanism http://rackhdci.lss.emc.com/blue/organizations/jenkins/ContinuousFunctionTest/detail/ContinuousFunctionTest/1202/pipeline/

### CODE REVIEW

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
@panpan0000 @changev @anhou @iceiilin

**Review by anhou — APPROVED** [review]
Thanks @PengTian0

**Review by panpan0000 — APPROVED** [review]
Leave a comment

**Pull request merged**
