### PR TITLE
[Skip CI]Jenkins change to reflect RackHD PR#632

### PR DESCRIPTION
**Pull request by panpan0000**
Jenkins: depends on https://github.com/RackHD/RackHD/pull/632

### CODE REVIEW

**Review by johren — APPROVED** [review]
Approved assuming that it has gone through some testing.

**Comment by PengTian0** [comment]
test this please

**Comment by panpan0000** [comment]
Yes, test done in PR RackHD/RackHD#632

**Comment by panpan0000** [comment]
Since we are moving the OVA-Post-Test running host from SH vCenter to US vSphere in https://github.com/RackHD/on-build-config/pull/141, so this PR ( which makes the output OVA with advanced pre-config-IP feature) is no longer needed .

close this PR

**Pull request closed without merging**
