### PR TITLE
Hot Fix(RAC-5091)  set +e around cleanup function

### PR DESCRIPTION
**Pull request by panpan0000**
@anhou  @iceiilin  @PengTian0 

Sandbox Test:   http://rackhdci.lss.emc.com/job/Archiving/job/build_ova/

### CODE REVIEW

**Comment by changev** [comment]
:+1:

**Review by anhou — APPROVED** [review]

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Pull request merged**
