### PR TITLE
generateSolLog missing

### PR DESCRIPTION
**Pull request by changev**
Recent updates delete the ```generateSolLog``` by mistake.

### CODE REVIEW

**Review by anhou — APPROVED** [review]

**Comment by PengTian0** [comment]
ova post missed sol log also

**Comment by changev** [comment]
@PengTian0 https://github.com/RackHD/on-build-config/pull/164
I've create the PR of archive ova post smoke test logs  2 days ago.

**Comment by PengTian0** [comment]
#164  just archives logs.
This PR is used to generate sol log.
You should generate sol log for ova post test too.

**Comment by changev** [comment]
@PengTian0 
That's another story for enhancing ova post test, will be far more complicated than this PR.

**Review by panpan0000 — APPROVED** [review]

**Pull request merged**
