### PR TITLE
add vanadium step: send result to database

### PR DESCRIPTION
**Pull request by PengTian0**
Add the step VTestResultsAnalyzerStep to send build result the test results to database.

### CODE REVIEW

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
@changev @yyscamper @anhou

**Review by keedya — CHANGES_REQUESTED** [review]
This PR depends on Moving the db server to hop lab

**Comment by PengTian0** [comment]
@keedya  Thanks for your reviewing.
I already moved the db server to the slave: [vmslave-packer-ova](http://rackhdci.lss.emc.com/computer/vmslave-packer-ova/configure)
The slave is on the same ESXI with the Jenkins server.

**Comment by keedya** [comment]
@PengTian0  i thought this VM is used for packer only.

**Comment by PengTian0** [comment]
@keedya 
Could you please help to set up a machine as the db server?

**Comment by keedya** [comment]
@PengTian0  of course, can you send me the details in a private email. I can set it up tomorrow

**Review by anhou — APPROVED** [review]

**Comment by PengTian0** [comment]
@keedya Thank you so much!
I will send you the email~

**Comment by changev** [comment]
:+1:  looks good.

**Pull request merged**
