### PR TITLE
vmslave-config: move some ci deps to rackhd deps for ucs

### PR DESCRIPTION
**Pull request by changev**
Repo ucs-service need the support of some python package, so move the packages from ci dependencies to rackhd dependencies.

@panpan0000 @Pengtian0

### CODE REVIEW

**Comment by panpan0000** [comment]
👍

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
@changev :
there's some discussion for ucs become a optional test component in CI. so if your PR being merged and then ucs become an option, then will some packages missing stop python scripts like FIT/build-release-tools being running ? (the package I mentioned like python-dev/python-pip...etc)
I meant, are you sure the python-dev/python-pip/libssl are all not needed for CI test if we don't consider ucs ?

**Comment by changev** [comment]
@panpan0000 
python-dev/python-pip/libssl are used contained in "ci dependency"
but when we import ucs service repo, cause it's a part of rackhd, so  python-dev/python-pip/libssl are moved to "rackhd dependency", and for reducing redundant they are removed from ci dependency.

So this is just a logic modification.

rackhd-dependency will be installed in both smoke test slave and **deb build slave**
but ci-dependency will just be install in smoke test slave.
So slaves with ci-dependency must also have rackhd dependency.

This is the difference so this PR is still valid.

**Comment by panpan0000** [comment]
talking with @changev , even if we remove the python-pip/python-dev when if all ucs-relevant dependency are removed in the ansible, it's still ok .
it will only impact the deb-build slave, the slaves running FIT will not be impacted and still have python dependency installed in other ansible playbooks.

:+1

**Review by panpan0000 — APPROVED** [review]

**Pull request merged**
