### PR TITLE
RAC-5160 :add double check if copy archive from PACKER_CACHE_BUILD job successful

### PR DESCRIPTION
**Pull request by panpan0000**
there's some possibility (like a sandbox jenkins env) , the PACKER_CACHE_BUILD is not ready yet.
so the folder will not exist. although there's set +e, but adding a check is preferred .

@hohene  @anhou  @iceiilin

### CODE REVIEW

**Comment by changev** [comment]
I noticed this "check" doesn't change any env var or export any new env var.

So I'm not unstanding the enhancement of this PR.

Can you please explain some details?

**Comment by panpan0000** [comment]
@changev , it will be double checked in following code in the same file:
```
if [ "$BUILD_TYPE" == "vmware" ] &&  [ -f output-vmware-iso/*.vmx ]; then
     echo "Build from template cache"
     export BUILD_STAGE=BUILD_FINAL
else
     echo "Build from begining"
     export BUILD_STAGE=BUILD_ALL
fi
```

**Comment by panpan0000** [comment]
test this please

**Comment by PengTian0** [comment]
If the job for cache is not ready, the step 
```  
                   step ([$class: 'CopyArtifact',
                    projectName: 'OVA_CACHE_BUILD',
                    target: 'cache_image']);
```
in build_ova.groovy(line 43) and build_vagrant.groovy(line 45) will fail.
If the pipeline goes to the shell build_ova.sh or build_vagrant.sh, the images are already copied.
So, in order to run build ova and build vagrant without cache job, we also need to wrap the step with ```try...catch```

**Comment by panpan0000** [comment]
@PengTian0 , Thank you for this great suggestion.
I've added the change per your advice.
please review again.

**Comment by PengTian0** [comment]
:+1:

**Comment by panpan0000** [comment]
+ @anhou  @iceiilin

**Comment by anhou** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
@anhou @iceiilin  , finally, the PR Gate pass :-) can you please merge it ?

**Review by anhou — APPROVED** [review]

**Review by iceiilin — APPROVED** [review]

**Pull request merged**
