### PR TITLE
add windows install regression test

### PR DESCRIPTION
**Pull request by tannoa2**

### CODE REVIEW

**Comment by tannoa2** [comment]
@keedya @jlongever @uppalk1 @zyoung51 @amymullins

**Comment by yyscamper** [comment]
:+1:

**Comment by tannoa2** [comment]
test this please

**Comment by keedya** [comment]
:+1:

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
Dear Jenkins, kindly, can you please, test this please

**Pull request merged**
