### PR TITLE
new feature: merge freezer

### PR DESCRIPTION
**Pull request by changev**
Add merge freezer to freeze or unfreeze PRs.
There will be a jenkins job to execute this freezer automatically.
Once master CI failed, it will freeze all open PRs, or CC can manually trigger this freezer.

Unfreeze all prs  need manually trigger.

This is test demo, **all text can be configurated**:
image
image

@panpan0000 @PengTian0

### CODE REVIEW

**Comment by johren** [comment]
Alan,  this looks like it will be helpful, but I'd like to understand how the manual freeze/unfreeze will work.  What will the CC need to do to freeze/unfreeze the PRs?

**Review by panpan0000 — APPROVED** [review]
+1 for this script.
But please show what the Jenkins job will be looked like and the usage( how the freeze/unfreeze is triggered )
also ,please show what the real freeze message will be looked like.

**Comment by changev** [comment]
@johren 
There'll be two usage scenarios.

**Automatic:**
When master CI pipeline broken, a freeze job will be triggered, this job will run continuously util master ci "green" or abort manually.
When master CI finished with green, **possible** running freeze job will be aborted and a unfreeze job will be triggered.
Tips:
* unfeeze action will do nothing on a normal(unfrozen) PR. 

**Manual:**(CC)
If CC want to freeze all prs manually, just trigger this job.
image

If unfreeze, CC should abort the freezing job first and  trigger a unfreeze job:
image

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Review by johren — DISMISSED** [review]
Thanks, @changev.  What do you mean by "this job will run continuously util master ci "green" or abort manually."  Wouldn't the job just run once at the end of the each MasterCI pipeline and freeze on red, unfreeze on green?   If it is already frozen, a second freeze would just keep it frozen and if it is already unfrozen, a second unfreeze would just keep it unfrozen.   I don't understand the need to run continuously.

Do you have an example of this job running in a sandbox?

**Comment by johren** [comment]
one more thing I just thought of when talking to Erika,
Does the freeze make it such that PRs cannot be merged?  If so, how do we merge a PR (or PRs) to fix the P1 issue?

**Comment by changev** [comment]
@johren 
1. MergeFreezer will just add a failure **commot status** to PRs, and it can't make a pr "can't be merged".
It's more like a symbol that reminds CC not to merge this PR. 

2. "this job will run continuously util master ci "green"
Sorry we just decide the scheme and there's not an active job now, I'll show it later.
* This script is "one-off". It runs once to freeze or unfreeze all current open PRs, when merge freeze, not only current prs but newly created prs also need to be frozen. So we use jenkins job to control the script to run continuously with a time interval. So freeze job won't end without external action.

* We need Automatic and Manual usage of this job.
In our design, in **automode**, masterCI "red or green" will automatically trigger a freeze or unfreeze job. When triggered, the job will **first abort all other active freeze or unfreeze builds**, and then run freeze or unfreeze.
But sometimes, we may need to control merge freeze more than depends on MasterCI. We may want to keep frozen even when MasterCI  turns green, or stop merge freeze even when MasterCI is still red.
So we can manually trigger a freeze or unfreeze build. Importantly, auto triggered freeze or unfreeze builds won't stop any manual builds, when it found manual builds, it'll exit directly.
This can be explained that manually trigger merge freeze will wrestle control of this job, manually trigger unfreeze will free the control.

**Comment by changev** [comment]
@johren 
You can try manually trigger freeze or unfreeze with this job 
http://10.62.59.175:8080/job/Blizzard-pipeline/

This is a auto trigger monitor job
http://10.62.59.175:8080/job/Bilzzard-Trigger/ 

PRs in https://github.com/RackHD-Mirror are used in these job.
You can create any PR for testing.

Thanks

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
@changev  @iceiilin @anhou 
please take care of this PR sooner.

**Review by iceiilin — APPROVED** [review]

**Pull request merged**
