### PR TITLE
suspend any running vagrant boxes before starting tests

### PR DESCRIPTION
**Pull request by geoff-reid**
@tannoa2 @uppalk1 @keedya @RackHD/corecommitters

### CODE REVIEW

**Comment by keedya** [comment]
:+1:

**Comment by changev** [comment]
@geoff-reid Thanks 

```
21:00:34 ==> dev: Setting the name of the VM: example_dev_1478772091199_20413
21:02:13 Vagrant cannot forward the specified ports on this VM, since they
21:02:13 would collide with some other application that is already listening
21:02:13 on these ports. The forwarded port to 9090 is already in use
21:02:13 on the host machine.
```

Are you trying to fix this "zombie virtualbox" issue (if I'm not mistaken)?
Actually I verified`vagrant suspend` can't kill or suspend a "zombie virtualbox".
The zombie box status is like `79a01cf  dev    virtualbox poweroff  /home/jenkins/workspace/ ......`
Only **kill process** can kill a "zombie virtualbox".

I suggest to find the zombie process like

```
onrack   15164 10274 15 Nov09 ?        02:50:58 /usr/lib/virtualbox/VBoxHeadless --comment vagrant_dev_1478706594114_3121 --startvm 55847974-0162-4893-8fe3-05f799914bd8 --vrde config
```

and just kill it.

Thanks again for solving this issue.

**Comment by geoff-reid** [comment]
@changev, this is not for the "zombie virtualbox" issue.  We keep hitting issues where developers are using the slave system during the day and leaving a vagrant box in the "running" state.  This running box causes all the nightly tests to fail due to a port collision.  The intent here is the suspend any boxes left running on the slave , this will save any open work, but allow the tests to run.

I am not familiar with the "zombie virtualbox" issue, do you have any more info about it ?

**Comment by changev** [comment]
+1

---

When Jenkins job is aborted abnormally(after vagrant up), jenkins has a chance to failed to destroy the virtualbox. Then a "zombie virtualbox" left. There's little information about the root cause of "zombie virtualbox", sorry I can't tell more about this issue.
Thanks.

**Review by anhou — APPROVED** [review]

**Review by keedya — APPROVED** [review]

**Pull request merged**
