### PR TITLE
support external rackhd config file

### PR DESCRIPTION
**Pull request by changev**
A configurable config.json file in rackhd test brings convenience.

RACKHD_CONFIG_FILE_URL can be set in job configuration to inject a config.json during function test

### CODE REVIEW

**Review by panpan0000 — APPROVED** [review]

**Comment by panpan0000** [comment]
BTW: why sandbox requires this PR to make masterCI pass ?

**Comment by changev** [comment]
@panpan0000 
Brief explanation:
1. when set default gateway in ova, it says "file already exists" But that's a new ova without any gateway.
But when ssh into ova and manually do the config, no error occurs. So retries are added to do this config.  
2. ova set gateway must be done before rackhd restart, otherwise on-http will throw error.
3. Unit test need sudo_pass but this var never be included into unit test. In prod jenkins no error occurs because prod jenkins vmslave are all sudo nopass. But not in the sandbox.
4. Sandbox need to use external config.json which contains local static file server.
5. Ignore unecessary port forward, otherwise docker ucs-service won't start normally.

**Comment by panpan0000** [comment]
for (1) , Do you root cause the problem of "file already exists" in a brand new OVA w/o gateway? Why retry can resolve it ?
for (3) , which lines of code reflect your SUDO_PASS change ?

**Comment by panpan0000** [comment]
RAC-5469  can be fixed by part of this PR(port forwarding)

**Comment by PengTian0** [comment]
:+1:

**Comment by changev** [comment]
@panpan0000 
(1) Don't know root cause now. I'll add some debug information in sandbox. 
(3) It's missing, now I add it again

**Review by panpan0000 — APPROVED** [review]
+1
since it address diff issues , it will be pretty to create diff PR for diff purpose if it's easy to split and independent.

for your ova-gate-way problem. we need to keep an eye and find a ultimate solution

**Review by anhou — APPROVED** [review]

**Pull request merged**
