### PR TITLE
Rac 4485 remove generated files

### PR DESCRIPTION
**Pull request by johren**
There are several files that are generated by build-config using *.in files.  The generated files should not be checked in to github.  They just confused people and cause them them wonder which files need to be modified.

### CODE REVIEW

**Comment by johren** [comment]
@panpan0000 @keedya @hohene

**Comment by hohene** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please
The status of the pull request is pending.
This PR https://github.com/RackHD/on-build-config/pull/129 fixed it

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
BUILD [on-build-config #1](http://147.178.202.18//blue/organizations/jenkins/on-build-config/detail/on-build-config/1/pipeline) : FAILURE

**Comment by PengTian0** [comment]
BUILD [on-build-config #2](http://147.178.202.18//blue/organizations/jenkins/on-build-config/detail/on-build-config/2/pipeline) : FAILURE

**Comment by PengTian0** [comment]
BUILD [on-build-config #3](http://147.178.202.18//blue/organizations/jenkins/on-build-config/detail/on-build-config/3/pipeline) : FAILURE

**Comment by PengTian0** [comment]
BUILD [on-build-config #4](http://147.178.202.18//blue/organizations/jenkins/on-build-config/detail/on-build-config/4/pipeline) : FAILURE

**Comment by PengTian0** [comment]
BUILD [on-build-config #6](http://147.178.202.18//blue/organizations/jenkins/on-build-config/detail/on-build-config/6/pipeline) : FAILURE

**Comment by panpan0000** [comment]
Good job ! I dislike that confusion also !  👍 
+ @changev  to double confirm.

**Comment by PengTian0** [comment]
test this please

**Pull request closed without merging**
