### PR TITLE
Modify dhcp config file for esxi 5.5

### PR DESCRIPTION
**Pull request by keedya**
-Remove options router and dns-name-server (needed for ubuntu installation)

@geoff-reid @tannoa2 @BillyAbildgaard @brianparry @uppalk1

### CODE REVIEW

**Review by geoff-reid — APPROVED** [review]
:+1:

**Comment by yyscamper** [comment]
@keedya : I remembered adding the `router` and `dns-name-server` is to pass the ubuntu installation, but now you removed it still because of ubuntu? I wonder what's the reason?

**Review by yyscamper — CHANGES_REQUESTED** [review]
request to clarify my last comment.

**Comment by keedya** [comment]
@yyscamper this fix is only for esxi5.5. firstboot fails if the options u mentioned are set

**Comment by yyscamper** [comment]
@keedya: isn't the ESXi and ubuntu tested together? So change either will impact another. Or you planed to deploy dedicated vagrant to test ESXi and Ubuntu separately?

**Comment by keedya** [comment]
@yyscamper they are not tested together. they run in separate jobs

**Comment by keedya** [comment]
@yyscamper check the link below:
http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-OS-Install/

**Review by yyscamper — APPROVED** [review]
Communicated with @keedya in Slack, different OS uses different job to test and use the test-group to distinguish OS, so this change will not impact ubuntu, the change makes sense to me.

**Pull request merged**
