### PR TITLE
bugfix: sol log missing

### PR DESCRIPTION
**Pull request by changev**
mount build-config to vagrant/src

then build-config/generate-sol-log.sh can be run inside vagrant.

@panpan0000 @PengTian0

### CODE REVIEW

**Comment by changev** [comment]
test this please

vmslave16 disk full

**Comment by changev** [comment]
test this please

**Review by yyscamper — APPROVED** [review]

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Review by anhou — APPROVED** [review]

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
@yyscamper 
Though this PR passed all tests, but it still can't fix the issue.
I'll reopen a PR.
Thanks

**Pull request merged**
