### PR TITLE
Bugfix/enhance discovery skip condition

### PR DESCRIPTION
**Pull request by changev**
enhance https://github.com/RackHD/RackHD/issues/270

Import a external value **NODES_NUMBER** ,which means how many nodes are used for test.
Now we have 3 vnodes for test, so `NODES_NUMBER = 3`

Enhanced node discovery test case skip condition, only if all nodes are truly discovered this case skip.

@iceiilin @panpan0000 @RackHD/corecommitters

### CODE REVIEW

**Comment by panpan0000** [comment]
This is a bad PR, please remove the Change for https://github.com/RackHD/on-build-config/pull/22

**Comment by panpan0000** [comment]
This is a conclusion after discussion with @jlongever  and @changev .
so it's fine to me ( resolve current issue only).
:+1:   , if add comment for this variable (example : why the number is 3)

**Comment by cgx027** [comment]
Looks good. :+1:

**Review by anhou — APPROVED** [review]
:+1:

**Review by yyscamper — APPROVED** [review]

**Pull request merged**
