### PR TITLE
[skip ci]Run MasterCI for on-build-config PR

### PR DESCRIPTION
**Pull request by PengTian0**
For RAC-4571: on-build-config PR Gate
The PR makes the on-build-config PR Gate run MasterCI pipeline.

@panpan0000 @changev @iceiilin @anhou 

Test Done:
The test job: http://rackhdci.lss.emc.com/job/on-build-config1/ 
It's already moved to http://rackhdci.lss.emc.com/job/Archiving/job/on-build-config1/

Change to Jenkins:
We need to change the configure of [on-build-config](http://rackhdci.lss.emc.com/job/on-build-config/) the same with the test job on-build-config1

@panpan0000 @changev @anhou @iceiilin

### CODE REVIEW

**Comment by changev** [comment]
BUILD [pipeline-prgate #3](http://147.178.202.18//blue/organizations/jenkins/pipeline-prgate/detail/pipeline-prgate/3/pipeline) : FAILURE

**Comment by panpan0000** [comment]
Good job!
1. can you please paste the pipeline view of this PR Gate ?
2. can you please share more details to CC/RackHD-CI forks?
3. can you please explain the details of where manifest was stored, where do the images go in publish step?

@johren  @keedya  @geoff-reid  @hohene  @iceiilin  @anhou

**Comment by PengTian0** [comment]
@panpan0000 Thanks!

1. The pipeline view of this PR Gate:
image

2. The pipeline imports a new Jenkinsfile for on-build-config PR Gate.
    steps:
    a. Run MasterCI pipeline
    b. Parse the tested PR and generate a manifest which contains the PR
    c. Write the result of pipeline to github.

3. The difference of the PR Gate with MasterCI:
    
- The PR Gate won't run stage ```publish```

- The PR Gate will upload manifest and debian packages to bintray/rackhd-mirror. In this way, it won't impact our MasterCI pipeline which restore manifest and debian packages to bintray/rackhd
- In order to save time and resources, the PR Gate won't run all the 5 test 
   docker post test : CIT and Install Centos6.5
        ova post test : FIT and Install ESXI 6.0
   The pipeline takes about 2hr20mins.
   We can reduce more test to save time by changing the job configuration.

**Comment by PengTian0** [comment]
the only concern to bring this PR online is it will compete the resource with MasterCI or SprintRelease .

**Review by panpan0000 — APPROVED** [review]
Pair review with @PengTian0 
+1

**Pull request merged**
