### PR TITLE
Rac 5000 5043 5060 convert smoke test OS install to FIT

### PR DESCRIPTION
**Pull request by gpaulos**
This PR converts all smoke OS installs to FIT.

@johren @hohene @patelb10

### CODE REVIEW

**Review by patelb10 — APPROVED** [review]

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Review by johren — APPROVED** [review]

**Pull request merged**
