### PR TITLE
RAC-4658:RackHD CI waiting for resources while resources are free and available

### PR DESCRIPTION
**Pull request by PengTian0**
Fix [RAC-4658](https://rackhd.atlassian.net/browse/RAC-4658)

### CODE REVIEW

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by keedya** [comment]
@PengTian0 what aboiout OS install? they can all be in one group

**Comment by PengTian0** [comment]
@keedya Sure! There are 2 groups: one for CIT and FIT, one for all OS install.

**Review by anhou — APPROVED** [review]

**Comment by keedya** [comment]
@RackHD/corecommitters please do not merge till we fix the UCS issue on some of the testing pools

**Comment by keedya** [comment]
@RackHD/corecommitters @PengTian0 confirmed tat there is no issue with slave 2-3 21 22 - 23 and FIt passed successfully 
+1

**Comment by anhou** [comment]
according to @PengTian0  this PR Jenkins test had pass, the running status is caused by all test reset. and this PR will help bunch test running, so I'll merge it directly.

**Comment by johren** [comment]
Why did this change go in when there was a "please do not merge" above and the test did not complete?  I'm not sure what an "all test reset" is.  Could the test have been run again?

**Pull request merged**
