### PR TITLE
PR gate supports interdependent PRs

### PR DESCRIPTION
**Pull request by changev**
1.  add pr_parser.py  for analysing PRs
2.  add commit-status-setter.py for commit status write back.
3.  edit some scripts for supporting interdependent PRs
4. Jenkins failed because my private repos are hard-code in changes for test.

**Comments have been written under every changes.**
**The email and slides inside helps to understand all the changes**.
**The merge won't affect production Jenkins**

This feature is on production jenkins  now.

### CODE REVIEW

**Comment by panpan0000** [comment]
test this please

**Comment by changev** [comment]
retest this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by heckj** [comment]
👍

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by anhou** [comment]
@changev The PR is conflict now, Is it still valid? if not, you could close it and resubmit when it's ready next time.

**Comment by changev** [comment]
@anhou I'll fix the conflicts.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Review by anhou — APPROVED** [review]

**Pull request merged**
