### PR TITLE
add ucs-service to docker builds

### PR DESCRIPTION
**Pull request by geoff-reid**
@RackHD/corecommitters  @RackHD/veyron @anhou @changev @PengTian0 

Successful test on Hop Jenkins Sandbox:  http://10.240.19.232:8080/blue/organizations/jenkins/MasterCI/detail/MasterCI/193/pipeline

### CODE REVIEW

**Comment by panpan0000** [comment]
this PR depends on https://github.com/RackHD/ucs-service/pull/20

👍  once PR Gate pass.

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Review by brianparry — APPROVED** [review]
:+1:

**Pull request merged**
