### PR TITLE
Edit Vagrantfile to adapt new version box: change foreman to pm2

### PR DESCRIPTION
**Pull request by changev**
In new version box 0.16,  RackHD process manage has been changed to PM2 instead of Foreman.
This PR is for that change.

see GG https://groups.google.com/forum/#!topic/rackhd/UfyZ1v9Gdc4

But 0.16 is compatible for using foreman nf start, so this PR is not urgent to be merged.

Related PR:
* https://github.com/RackHD/RackHD/pull/478  edit packer script, change foreman to pm2.
* https://github.com/RackHD/RackHD/pull/479  edit RackHD readme 
* https://github.com/RackHD/docs/pull/357 edit docs
@panpan0000

### CODE REVIEW

**Comment by panpan0000** [comment]
this PR depends on new 0.16 Vagrant Box uploaded to ATLAS

**Comment by panpan0000** [comment]
:+1:

**Comment by panpan0000** [comment]
test this please

**Review by yyscamper — APPROVED** [review]

**Comment by changev** [comment]
New version vagrant box 0.16 has been available and passed simple test. But for stability I'll use it in ShangHai local continuous test see if there's any potential problems.

This PR shouldn't be merge until make sure new vagrant box is good enough. 

---

Stability  has been validated, so this PR can be merged.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Pull request merged**
