### PR TITLE
bugfix: vagrant post test not valid

### PR DESCRIPTION
**Pull request by changev**
Vagrant post test does not meet the existing requirements.

This PR did some enhancement of that.

skip CI
@panpan0000 @PengTian0

### CODE REVIEW

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
@changev, so where does the vagrant file passed in as parameter in command line come from ?

**Comment by changev** [comment]
@panpan0000 Thanks.
In jenkins the vagrantfile is downloaded from my private repo.
It's a vagrantfile template.
We should consider to move it to on-build-config repo.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
:+1:   if Jenkins test pass

**Comment by PengTian0** [comment]
:+1:

**Review by yyscamper — APPROVED** [review]

**Pull request merged**
