### PR TITLE
mount build-config to vagrant/src

### PR DESCRIPTION
**Pull request by changev**
mount build-config to vagrant/src

then build-config/generate-sol-log.sh can be run inside vagrant.

@panpan0000 @PengTian0

### CODE REVIEW

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
http://10.240.19.21/job/on-build-config/275/

sol log was archived successfully

**Review by yyscamper — APPROVED** [review]

**Comment by PengTian0** [comment]
:+1:

**Pull request merged**
